--- #YAML:1.0
name:                Video-Capture-V4l-Imager
version:             0.01
abstract:            Capture images from a video webcam
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Imager:                        0.49
    Inline::C:                     0.44
    Log::Log4perl:                 1.06
    Video::Capture::V4l:           0.9
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
